export const school_data = [
  {
    id: 1,
    description: "Daftar katakli qizlar uchun, 48 varaq, 5 dona",
    rate: 5,
    review: 23,
    real_price: 12000,
    discount_price: 13000,
    price_per_month: 1444,
    product_badge: "Maktab bozori",
    image: "/data-img/img1.jpg",
  },
  {
    id: 2,
    description: "Maktab qalam qutisi, zamokda, 20 * 5 sm",
    rate: 5,
    review: 23,
    real_price: 500,
    price_per_month: 1444,
    discount_price: 600,
    product_badge: "Maktab bozori",
    image: "/data-img/img2.jpg",
  },
  {
    id: 3,
    description: "Maktab buyumlari to'plami, 36 narsa",
    rate: 5,
    review: 5,
    real_price: 150000,
    price_per_month: 1444,
    discount_price: 100000,
    product_badge: "Maktab bozori",
    image: "/data-img/img3.jpg",
  },
  {
    id: 4,
    description: "O'g'il bolalar uchun ko'ylak",
    rate: 5,
    review: 23,
    real_price: 12000,
    price_per_month: 1444,
    discount_price: 13000,
    product_badge: "Maktab bozori",
    image: "/data-img/img4.jpg",
  },
  {
    id: 5,
    description:
      "Noutbuk Lenovo V15 Intel Celeron N4020 DDR4 4, 256 GB SSD, Iron Grey, 15.6",
    rate: 4,
    review: 2,
    real_price: 100000,
    price_per_month: 1444,
    discount_price: 170000,
    product_badge: "Maktab bozori",
    image: "/data-img/img5.jpg",
  },
  {
    id: 6,
    description: "Daftar katakli qizlar uchun, 48 varaq, 5 dona",
    rate: 5,
    review: 23,
    real_price: 12000,
    discount_price: 13000,
    price_per_month: 1444,
    product_badge: "Maktab bozori",
    image: "/data-img/img1.jpg",
  },
  {
    id: 7,
    description: "Maktab qalam qutisi, zamokda, 20 * 5 sm",
    rate: 5,
    review: 23,
    real_price: 500,
    price_per_month: 1444,
    discount_price: 600,
    product_badge: "Maktab bozori",
    image: "/data-img/img2.jpg",
  },
  {
    id: 8,
    description: "Maktab buyumlari to'plami, 36 narsa",
    rate: 5,
    review: 5,
    real_price: 150000,
    price_per_month: 1444,
    discount_price: 100000,
    product_badge: "Maktab bozori",
    image: "/data-img/img3.jpg",
  },
  {
    id: 9,
    description: "O'g'il bolalar uchun ko'ylak",
    rate: 5,
    review: 23,
    real_price: 12000,
    price_per_month: 1444,
    discount_price: 13000,
    product_badge: "Maktab bozori",
    image: "/data-img/img4.jpg",
  },
  {
    id: 10,
    description:
      "Noutbuk Lenovo V15 Intel Celeron N4020 DDR4 4, 256 GB SSD, Iron Grey, 15.6",
    rate: 4,
    review: 2,
    real_price: 100000,
    price_per_month: 1444,
    discount_price: 170000,
    product_badge: "Maktab bozori",
    image: "/data-img/img5.jpg",
  },
  {
    id: 11,
    description: "Daftar katakli qizlar uchun, 48 varaq, 5 dona",
    rate: 5,
    review: 23,
    real_price: 12000,
    discount_price: 13000,
    price_per_month: 1444,
    product_badge: "Maktab bozori",
    image: "/data-img/img1.jpg",
  },
  {
    id: 12,
    description: "Maktab qalam qutisi, zamokda, 20 * 5 sm",
    rate: 5,
    review: 23,
    real_price: 500,
    price_per_month: 1444,
    discount_price: 600,
    product_badge: "Maktab bozori",
    image: "/data-img/img2.jpg",
  },
  {
    id: 13,
    description: "Maktab buyumlari to'plami, 36 narsa",
    rate: 5,
    review: 5,
    real_price: 150000,
    price_per_month: 1444,
    discount_price: 100000,
    product_badge: "Maktab bozori",
    image: "/data-img/img3.jpg",
  },
  {
    id: 14,
    description: "O'g'il bolalar uchun ko'ylak",
    rate: 5,
    review: 23,
    real_price: 12000,
    price_per_month: 1444,
    discount_price: 13000,
    product_badge: "Maktab bozori",
    image: "/data-img/img4.jpg",
  },
  {
    id: 15,
    description:
      "Noutbuk Lenovo V15 Intel Celeron N4020 DDR4 4, 256 GB SSD, Iron Grey, 15.6",
    rate: 4,
    review: 2,
    real_price: 100000,
    price_per_month: 1444,
    discount_price: 170000,
    product_badge: "Maktab bozori",
    image: "/data-img/img5.jpg",
  },
  // {
  //   id: 16,
  //   description: "Daftar katakli qizlar uchun, 48 varaq, 5 dona",
  //   rate: 5,
  //   review: 23,
  //   real_price: 12000,
  //   discount_price: 13000,
  //   price_per_month: 1444,
  //   product_badge: "Maktab bozori",
  //   image: "/data-img/img1.jpg",
  // },
  // {
  //   id: 17,
  //   description: "Maktab qalam qutisi, zamokda, 20 * 5 sm",
  //   rate: 5,
  //   review: 23,
  //   real_price: 500,
  //   price_per_month: 1444,
  //   discount_price: 600,
  //   product_badge: "Maktab bozori",
  //   image: "/data-img/img2.jpg",
  // },
  // {
  //   id: 18,
  //   description: "Maktab buyumlari to'plami, 36 narsa",
  //   rate: 5,
  //   review: 5,
  //   real_price: 150000,
  //   price_per_month: 1444,
  //   discount_price: 100000,
  //   product_badge: "Maktab bozori",
  //   image: "/data-img/img3.jpg",
  // },
  // {
  //   id: 19,
  //   description: "O'g'il bolalar uchun ko'ylak",
  //   rate: 5,
  //   review: 23,
  //   real_price: 12000,
  //   price_per_month: 1444,
  //   discount_price: 13000,
  //   product_badge: "Maktab bozori",
  //   image: "/data-img/img4.jpg",
  // },
  // {
  //   id: 20,
  //   description:
  //     "Noutbuk Lenovo V15 Intel Celeron N4020 DDR4 4, 256 GB SSD, Iron Grey, 15.6",
  //   rate: 4,
  //   review: 2,
  //   real_price: 100000,
  //   price_per_month: 1444,
  //   discount_price: 170000,
  //   product_badge: "Maktab bozori",
  //   image: "/data-img/img5.jpg",
  // },
];
